#!/bin/sh

if [ -f /var/mobile/Library/Application\ Support/OS\ Experience/OS\ Experience.dylib ]; then
	echo Removing license...
	rm /var/mobile/Library/Application\ Support/OS\ Experience/OS\ Experience.dylib
fi